variables:
  CARGO_REGISTRY_TOKEN: "$CARGO_REGISTRY_TOKEN"

stages:
  - lint
  - build
  - publish

fmt:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --version
    - cargo fmt --all -- --check

build:
  stage: build
  image: rust:latest
  script:
    - cargo b --verbose
    - cargo t --verbose

publish:
  stage: publish
  image: rust:latest
  script:
    - cargo b --verbose
    - cargo publish -p tpm2_class
    - cargo publish -p tpm2_cli
  only:
    - tags
