matrix:
  RUST: [stable, beta, nightly]

steps:
  test:
    when:
      event: [push, pull_request]
    image: rust
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default $RUST
      - rustup component add clippy
      - rustup component add rustfmt
      - cargo check
      - cargo fmt --version
      - cargo fmt --all -- --check
      - cargo clippy
      - cargo test
