[package]
name = "tpm2_call"
description = "TPM 2.0 library protocol"
version = "0.1.0"
license = "MIT"
homepage = "https://gitlab.com/tpm2_library"
repository = "https://gitlab.com/tpm2_library.git"
edition = "2021"
rust-version = "1.78"

[dependencies]
strum_macros = "0.26.4"
